include ../../config.mk\


SRC = ${wildcard *.c}
OBJ = ${SRC:.c=.o}
DEP = ${SRC:.c=.d}
BIN = \
	program-2-1 \
	program-2-2 \
	program-2-3 \
	program-2-4 \
	program-2-5 \

include ../../util.mk

program-2-1: program-2-1.o
program-2-2: program-2-2.o
program-2-3: program-2-3.o
program-2-4: program-2-4.o
program-2-5: program-2-5.o
