include ../../config.mk


SRC = ${wildcard *.c}
OBJ = ${SRC:.c=.o}
DEP = ${SRC:.c=.d}
BIN = \
	program-6-1\
	program-6-2\
	program-6-3\
	program-6-4\
	program-6-5\
	program-6-6\
	program-6-7\
	program-6-8

include ../../util.mk

program-6-1: program-6-1.o
program-6-2: program-6-2.o
program-6-3: program-6-3.o
program-6-4: program-6-4.o
program-6-5: program-6-5.o
program-6-6: program-6-6.o
program-6-7: program-6-7.o
program-6-8: program-6-8.o
