include ../../config.mk


SRC = ${wildcard *.c}
OBJ = ${SRC:.c=.o}
DEP = ${SRC:.c=.d}
BIN = \
	program-6-1\
	program-6-2\
	program-6-3

include ../../util.mk

program-6-1: program-6-1.o
program-6-2: program-6-2.o
