include ../../config.mk


SRC = ${wildcard *.c}
OBJ = ${SRC:.c=.o}
DEP = ${SRC:.c=.d}
BIN = \
	program-7-1\
	program-7-2\
	program-7-3\
	program-7-4\
	program-7-5\
	program-7-6\
	program-7-7

include ../../util.mk

program-7-1: program-7-1.o
program-7-2: program-7-2.o
program-7-3: program-7-3.o
program-7-4: program-7-4.o
program-7-5: program-7-5.o
program-7-6: program-7-6.o
program-7-7: program-7-7.o
